const MovieActionTypes = {
  SET_MOVIE_DATA_START: "SET_MOVIE_DATA_START",
  SET_MOVIE_DATA: "SET_MOVIE_DATA",
  SET_MOVIE_GRID_DATA: "SET_MOVIE_GRID_DATA",
  SET_MOVIE_DATA_SUCCESS: "SET_MOVIE_DATA_SUCCESS",
};

export default MovieActionTypes;
